"""initial_schema

Revision ID: b1130d605f93
Revises: 
Create Date: 2026-05-10 13:28:38.533137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1130d605f93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# EncryptedString stores as LargeBinary (BYTEA)
EncryptedString = sa.LargeBinary


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('resource_detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('phi_accessed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('payers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payer_name', sa.String(length=255), nullable=False),
    sa.Column('payer_id_number', sa.String(length=20), nullable=False),
    sa.Column('payer_type', sa.String(length=20), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('portal_url', sa.String(length=500), nullable=True),
    sa.Column('clearinghouse', sa.String(length=100), nullable=True),
    sa.Column('timely_filing_days', sa.Integer(), nullable=False),
    sa.Column('appeal_filing_days', sa.Integer(), nullable=False),
    sa.Column('electronic_payer', sa.Boolean(), nullable=False),
    sa.Column('era_enrolled', sa.Boolean(), nullable=False),
    sa.Column('eft_enrolled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payer_id_number')
    )
    op.create_index('idx_payers_pid', 'payers', ['payer_id_number'], unique=False)
    op.create_index('idx_payers_type', 'payers', ['payer_type'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'resource', 'action', name='uq_permissions_role_resource_action')
    )
    op.create_table('practices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('tin', EncryptedString(), nullable=False),
    sa.Column('group_npi', sa.String(length=10), nullable=True),
    sa.Column('specialty_primary', sa.String(length=100), nullable=True),
    sa.Column('specialty_codes', sa.ARRAY(sa.String(length=20)), nullable=True),
    sa.Column('address_line_1', sa.Text(), nullable=True),
    sa.Column('address_line_2', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('onboarded_at', sa.DateTime(), nullable=True),
    sa.Column('go_live_date', sa.Date(), nullable=True),
    sa.Column('terminated_at', sa.DateTime(), nullable=True),
    sa.Column('termination_reason', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('intake_method', sa.String(length=20), nullable=False),
    sa.Column('default_clearinghouse', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_practices_created_by', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_practices_status', 'practices', ['status'], unique=False)
    op.create_index('idx_practices_tin', 'practices', ['tin'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('npi', sa.String(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('credential', sa.String(length=20), nullable=True),
    sa.Column('taxonomy_code', sa.String(length=20), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('tin', EncryptedString(), nullable=True),
    sa.Column('is_individual', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('npi')
    )
    op.create_table('client_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('billing_period_start', sa.Date(), nullable=False),
    sa.Column('billing_period_end', sa.Date(), nullable=False),
    sa.Column('total_collections', sa.Float(), nullable=False),
    sa.Column('total_claims_submitted', sa.Integer(), nullable=True),
    sa.Column('fee_model_used', sa.String(length=20), nullable=False),
    sa.Column('calculated_fee', sa.Float(), nullable=False),
    sa.Column('minimum_fee_applied', sa.Boolean(), nullable=False),
    sa.Column('adjustments', sa.Float(), nullable=False),
    sa.Column('total_due', sa.Float(), nullable=False),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index('idx_invoices_period', 'client_invoices', ['billing_period_start', 'billing_period_end'], unique=False)
    op.create_index('idx_invoices_practice', 'client_invoices', ['practice_id'], unique=False)
    op.create_index('idx_invoices_status', 'client_invoices', ['status'], unique=False)
    op.create_table('fee_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('mrn', sa.String(length=50), nullable=False),
    sa.Column('first_name', EncryptedString(), nullable=False),
    sa.Column('last_name', EncryptedString(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('ssn_encrypted', EncryptedString(), nullable=True),
    sa.Column('address_line_1', sa.Text(), nullable=True),
    sa.Column('address_line_2', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mrn')
    )
    op.create_index('idx_patients_dob', 'patients', ['date_of_birth'], unique=False)
    op.create_index('idx_patients_mrn', 'patients', ['mrn'], unique=False)
    op.create_index('idx_patients_name', 'patients', ['last_name', 'first_name'], unique=False)
    op.create_index('idx_patients_practice', 'patients', ['practice_id'], unique=False)
    op.create_table('payer_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=True),
    sa.Column('icd10_code', sa.String(length=10), nullable=True),
    sa.Column('rule_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payer_rules_cpt', 'payer_rules', ['cpt_code'], unique=False)
    op.create_index('idx_payer_rules_payer', 'payer_rules', ['payer_id'], unique=False)
    op.create_index('idx_payer_rules_type', 'payer_rules', ['rule_type'], unique=False)
    op.create_table('practice_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('address_line_1', sa.Text(), nullable=False),
    sa.Column('address_line_2', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('place_of_service', sa.String(length=5), nullable=False),
    sa.Column('facility_npi', sa.String(length=10), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_locations_practice', 'practice_locations', ['practice_id'], unique=False)
    op.create_table('service_agreements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('fee_model', sa.String(length=20), nullable=False),
    sa.Column('percentage_rate', sa.Float(), nullable=True),
    sa.Column('per_claim_rate', sa.Float(), nullable=True),
    sa.Column('flat_fee_monthly', sa.Float(), nullable=True),
    sa.Column('hybrid_base_fee', sa.Float(), nullable=True),
    sa.Column('hybrid_threshold', sa.Float(), nullable=True),
    sa.Column('hybrid_overage_rate', sa.Float(), nullable=True),
    sa.Column('minimum_monthly_fee', sa.Float(), nullable=True),
    sa.Column('includes_coding', sa.Boolean(), nullable=False),
    sa.Column('includes_billing', sa.Boolean(), nullable=False),
    sa.Column('includes_posting', sa.Boolean(), nullable=False),
    sa.Column('includes_denials', sa.Boolean(), nullable=False),
    sa.Column('includes_credentialing', sa.Boolean(), nullable=False),
    sa.Column('includes_eligibility', sa.Boolean(), nullable=False),
    sa.Column('includes_patient_collections', sa.Boolean(), nullable=False),
    sa.Column('includes_reporting', sa.Boolean(), nullable=False),
    sa.Column('sla_clean_claim_rate', sa.Float(), nullable=False),
    sa.Column('sla_days_to_submit', sa.Integer(), nullable=False),
    sa.Column('sla_appeal_turnaround', sa.Integer(), nullable=False),
    sa.Column('sla_posting_turnaround', sa.Integer(), nullable=False),
    sa.Column('sla_denial_response', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('notice_period_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agreements_practice', 'service_agreements', ['practice_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=True),
    sa.Column('internal_role', sa.String(length=30), nullable=True),
    sa.Column('provider_role', sa.String(length=30), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', EncryptedString(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_practice', 'users', ['practice_id'], unique=False)
    op.create_index('idx_users_type', 'users', ['user_type'], unique=False)
    op.create_table('charge_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('intake_method', sa.String(length=20), nullable=False),
    sa.Column('source_file_id', sa.Uuid(), nullable=True),
    sa.Column('total_charges', sa.Integer(), nullable=False),
    sa.Column('processed_charges', sa.Integer(), nullable=False),
    sa.Column('error_charges', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_charge_batches_practice', 'charge_batches', ['practice_id'], unique=False)
    op.create_index('idx_charge_batches_status', 'charge_batches', ['status'], unique=False)
    op.create_table('coverages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.String(length=50), nullable=False),
    sa.Column('group_number', sa.String(length=50), nullable=True),
    sa.Column('plan_name', sa.String(length=255), nullable=True),
    sa.Column('plan_type', sa.String(length=20), nullable=True),
    sa.Column('coverage_type', sa.String(length=20), nullable=False),
    sa.Column('subscriber_relation', sa.String(length=20), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('copay_amount', sa.Float(), nullable=True),
    sa.Column('deductible_amount', sa.Float(), nullable=True),
    sa.Column('deductible_met', sa.Float(), nullable=True),
    sa.Column('coinsurance_pct', sa.Float(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_coverages_member', 'coverages', ['member_id'], unique=False)
    op.create_index('idx_coverages_patient', 'coverages', ['patient_id'], unique=False)
    op.create_index('idx_coverages_payer', 'coverages', ['payer_id'], unique=False)
    op.create_index('idx_coverages_practice', 'coverages', ['practice_id'], unique=False)
    op.create_table('encounters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('encounter_type', sa.String(length=20), nullable=False),
    sa.Column('encounter_date', sa.Date(), nullable=False),
    sa.Column('admit_date', sa.Date(), nullable=True),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.Column('place_of_service', sa.String(length=5), nullable=False),
    sa.Column('referring_provider_id', sa.UUID(), nullable=True),
    sa.Column('prior_auth_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('document_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['referring_provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_encounters_date', 'encounters', ['encounter_date'], unique=False)
    op.create_index('idx_encounters_patient', 'encounters', ['patient_id'], unique=False)
    op.create_index('idx_encounters_practice', 'encounters', ['practice_id'], unique=False)
    op.create_index('idx_encounters_status', 'encounters', ['status'], unique=False)
    op.create_table('fee_schedule_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fee_schedule_id', sa.UUID(), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('modifier', sa.String(length=5), nullable=True),
    sa.Column('place_of_service', sa.String(length=5), nullable=True),
    sa.Column('allowed_amount', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['fee_schedule_id'], ['fee_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fee_schedule_id', 'cpt_code', 'modifier', 'place_of_service', 'effective_date', name='uq_fsr_unique_rate')
    )
    op.create_index('idx_fsr_cpt', 'fee_schedule_rates', ['cpt_code'], unique=False)
    op.create_index('idx_fsr_schedule', 'fee_schedule_rates', ['fee_schedule_id'], unique=False)
    op.create_table('payer_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('group_number', sa.String(length=50), nullable=True),
    sa.Column('provider_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('edi_payer_id', sa.String(length=20), nullable=True),
    sa.Column('era_enrolled', sa.Boolean(), nullable=False),
    sa.Column('era_enrollment_date', sa.Date(), nullable=True),
    sa.Column('eft_enrolled', sa.Boolean(), nullable=False),
    sa.Column('eft_enrollment_date', sa.Date(), nullable=True),
    sa.Column('clearinghouse', sa.String(length=100), nullable=True),
    sa.Column('sender_id', sa.String(length=50), nullable=True),
    sa.Column('receiver_id', sa.String(length=50), nullable=True),
    sa.Column('timely_filing_days', sa.Integer(), nullable=True),
    sa.Column('appeal_filing_days', sa.Integer(), nullable=True),
    sa.Column('appeal_address', sa.Text(), nullable=True),
    sa.Column('appeal_fax', sa.String(length=20), nullable=True),
    sa.Column('payer_portal_url', sa.String(length=500), nullable=True),
    sa.Column('payer_portal_login', EncryptedString(), nullable=True),
    sa.Column('payer_phone', sa.String(length=20), nullable=True),
    sa.Column('payer_rep_name', sa.String(length=200), nullable=True),
    sa.Column('fee_schedule_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fee_schedule_id'], ['fee_schedules.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practice_id', 'payer_id', name='uq_payer_enrollment_practice_payer')
    )
    op.create_index('idx_enrollments_payer', 'payer_enrollments', ['payer_id'], unique=False)
    op.create_index('idx_enrollments_practice', 'payer_enrollments', ['practice_id'], unique=False)
    op.create_table('payment_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('check_number', sa.String(length=50), nullable=True),
    sa.Column('eft_trace', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('total_paid', sa.Float(), nullable=False),
    sa.Column('total_claims', sa.Integer(), nullable=False),
    sa.Column('era_file_id', sa.Uuid(), nullable=True),
    sa.Column('production_date', sa.Date(), nullable=True),
    sa.Column('deposit_date', sa.Date(), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('posted_by', sa.UUID(), nullable=True),
    sa.Column('auto_posted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], ),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_batch_check', 'payment_batches', ['check_number'], unique=False)
    op.create_index('idx_payment_batch_payer', 'payment_batches', ['payer_id'], unique=False)
    op.create_index('idx_payment_batch_practice', 'payment_batches', ['practice_id'], unique=False)
    op.create_index('idx_payment_batch_status', 'payment_batches', ['status'], unique=False)
    op.create_table('portal_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_unread', 'portal_notifications', ['is_read', 'user_id'], unique=False)
    op.create_index('idx_notifications_user', 'portal_notifications', ['user_id'], unique=False)
    op.create_table('staff_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_in_practice', sa.String(length=30), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'practice_id', 'role_in_practice', name='uq_staff_assignment')
    )
    op.create_index('idx_assignments_practice', 'staff_assignments', ['practice_id'], unique=False)
    op.create_index('idx_assignments_user', 'staff_assignments', ['user_id'], unique=False)
    op.create_table('staff_productivity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('queue_type', sa.String(length=20), nullable=False),
    sa.Column('items_completed', sa.Integer(), nullable=False),
    sa.Column('total_time_seconds', sa.Integer(), nullable=False),
    sa.Column('avg_time_per_item', sa.Integer(), nullable=False),
    sa.Column('errors_found', sa.Integer(), nullable=False),
    sa.Column('claims_submitted', sa.Integer(), nullable=True),
    sa.Column('claims_dollar_amount', sa.Float(), nullable=True),
    sa.Column('payments_posted', sa.Integer(), nullable=True),
    sa.Column('payments_dollar_amount', sa.Float(), nullable=True),
    sa.Column('denials_worked', sa.Integer(), nullable=True),
    sa.Column('denials_dollar_recovered', sa.Float(), nullable=True),
    sa.Column('codes_reviewed', sa.Integer(), nullable=True),
    sa.Column('coding_accuracy_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'practice_id', 'date', 'queue_type', name='uq_productivity')
    )
    op.create_index('idx_productivity_practice', 'staff_productivity', ['practice_id', 'date'], unique=False)
    op.create_index('idx_productivity_user', 'staff_productivity', ['user_id', 'date'], unique=False)
    op.create_table('work_queue_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('queue_type', sa.String(length=20), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('sla_breached', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_queue_assigned', 'work_queue_items', ['assigned_to', 'status'], unique=False)
    op.create_index('idx_queue_practice', 'work_queue_items', ['practice_id'], unique=False)
    op.create_index('idx_queue_priority', 'work_queue_items', ['priority', 'due_date'], unique=False)
    op.create_index('idx_queue_sla', 'work_queue_items', ['sla_breached'], unique=False, postgresql_where=sa.text('sla_breached = TRUE'))
    op.create_index('idx_queue_type_status', 'work_queue_items', ['queue_type', 'status'], unique=False)
    op.create_table('charge_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('patient_name_submitted', sa.String(length=200), nullable=True),
    sa.Column('patient_dob_submitted', sa.Date(), nullable=True),
    sa.Column('patient_mrn_submitted', sa.String(length=50), nullable=True),
    sa.Column('rendering_provider_id', sa.UUID(), nullable=True),
    sa.Column('referring_provider_name', sa.String(length=200), nullable=True),
    sa.Column('referring_provider_npi', sa.String(length=10), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('place_of_service', sa.String(length=5), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('diagnosis_codes', sa.ARRAY(sa.String(length=10)), nullable=True),
    sa.Column('procedure_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('needs_coding', sa.Boolean(), nullable=False),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('document_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('superbill_image_id', sa.Uuid(), nullable=True),
    sa.Column('primary_payer_id', sa.UUID(), nullable=True),
    sa.Column('member_id', sa.String(length=50), nullable=True),
    sa.Column('authorization_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('provider_notified', sa.Boolean(), nullable=False),
    sa.Column('provider_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['charge_batches.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['practice_locations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['primary_payer_id'], ['payers.id'], ),
    sa.ForeignKeyConstraint(['rendering_provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_charges_assigned', 'charge_entries', ['assigned_to'], unique=False)
    op.create_index('idx_charges_date', 'charge_entries', ['service_date'], unique=False)
    op.create_index('idx_charges_practice', 'charge_entries', ['practice_id'], unique=False)
    op.create_index('idx_charges_status', 'charge_entries', ['status'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('claim_number', sa.String(length=50), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('coverage_id', sa.UUID(), nullable=False),
    sa.Column('rendering_provider', sa.UUID(), nullable=False),
    sa.Column('billing_provider', sa.UUID(), nullable=False),
    sa.Column('claim_type', sa.String(length=5), nullable=False),
    sa.Column('frequency_code', sa.String(length=2), nullable=False),
    sa.Column('total_charge', sa.Float(), nullable=False),
    sa.Column('total_paid', sa.Float(), nullable=False),
    sa.Column('total_adjusted', sa.Float(), nullable=False),
    sa.Column('patient_responsibility', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('adjudication_date', sa.DateTime(), nullable=True),
    sa.Column('timely_filing_deadline', sa.Date(), nullable=True),
    sa.Column('clearinghouse_id', sa.String(length=100), nullable=True),
    sa.Column('clearinghouse_ref', sa.String(length=100), nullable=True),
    sa.Column('edi_837_file_id', sa.Uuid(), nullable=True),
    sa.Column('scrub_score', sa.Integer(), nullable=True),
    sa.Column('denial_risk_score', sa.Float(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('draft','scrubbing','scrub_failed','ready','submitted','accepted','rejected','paid','partial_paid','denied','appealed','closed')", name='ck_claims_status'),
    sa.ForeignKeyConstraint(['billing_provider'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverages.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['rendering_provider'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_number')
    )
    op.create_index('idx_claims_encounter', 'claims', ['encounter_id'], unique=False)
    op.create_index('idx_claims_number', 'claims', ['claim_number'], unique=False)
    op.create_index('idx_claims_patient', 'claims', ['patient_id'], unique=False)
    op.create_index('idx_claims_payer', 'claims', ['payer_id'], unique=False)
    op.create_index('idx_claims_practice', 'claims', ['practice_id'], unique=False)
    op.create_index('idx_claims_status', 'claims', ['status'], unique=False)
    op.create_index('idx_claims_submission', 'claims', ['submission_date'], unique=False)
    op.create_table('coding_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('coder_id', sa.UUID(), nullable=True),
    sa.Column('document_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('nlp_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_model_version', sa.String(length=50), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('suggested_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_started_at', sa.DateTime(), nullable=True),
    sa.Column('review_completed_at', sa.DateTime(), nullable=True),
    sa.Column('review_time_seconds', sa.Integer(), nullable=True),
    sa.Column('coder_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_coding_coder', 'coding_sessions', ['coder_id'], unique=False)
    op.create_index('idx_coding_encounter', 'coding_sessions', ['encounter_id'], unique=False)
    op.create_index('idx_coding_practice', 'coding_sessions', ['practice_id'], unique=False)
    op.create_index('idx_coding_status', 'coding_sessions', ['status'], unique=False)
    op.create_table('claim_diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('icd10_code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'sequence_number', name='uq_claim_dx_sequence')
    )
    op.create_index('idx_claim_dx_claim', 'claim_diagnoses', ['claim_id'], unique=False)
    op.create_index('idx_claim_dx_code', 'claim_diagnoses', ['icd10_code'], unique=False)
    op.create_table('claim_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('cpt_description', sa.Text(), nullable=True),
    sa.Column('icd_pointer_1', sa.String(length=10), nullable=True),
    sa.Column('icd_pointer_2', sa.String(length=10), nullable=True),
    sa.Column('icd_pointer_3', sa.String(length=10), nullable=True),
    sa.Column('icd_pointer_4', sa.String(length=10), nullable=True),
    sa.Column('modifier_1', sa.String(length=5), nullable=True),
    sa.Column('modifier_2', sa.String(length=5), nullable=True),
    sa.Column('modifier_3', sa.String(length=5), nullable=True),
    sa.Column('modifier_4', sa.String(length=5), nullable=True),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('charge_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('allowed_amount', sa.Float(), nullable=True),
    sa.Column('service_date_from', sa.Date(), nullable=False),
    sa.Column('service_date_to', sa.Date(), nullable=True),
    sa.Column('place_of_service', sa.String(length=5), nullable=True),
    sa.Column('ndc_code', sa.String(length=20), nullable=True),
    sa.Column('revenue_code', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'line_number', name='uq_claim_line_number')
    )
    op.create_index('idx_claim_lines_claim', 'claim_lines', ['claim_id'], unique=False)
    op.create_index('idx_claim_lines_cpt', 'claim_lines', ['cpt_code'], unique=False)
    op.create_table('claim_scrub_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('claim_line_id', sa.UUID(), nullable=True),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('auto_fixable', sa.Boolean(), nullable=False),
    sa.Column('auto_fixed', sa.Boolean(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['claim_line_id'], ['claim_lines.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scrub_claim', 'claim_scrub_results', ['claim_id'], unique=False)
    op.create_index('idx_scrub_severity', 'claim_scrub_results', ['severity'], unique=False)
    op.create_table('payment_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=True),
    sa.Column('claim_line_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('claim_number_reported', sa.String(length=50), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('cpt_code', sa.String(length=10), nullable=True),
    sa.Column('billed_amount', sa.Float(), nullable=True),
    sa.Column('allowed_amount', sa.Float(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('patient_responsibility', sa.Float(), nullable=False),
    sa.Column('match_status', sa.String(length=20), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('is_underpaid', sa.Boolean(), nullable=False),
    sa.Column('underpayment_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['payment_batches.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['claim_line_id'], ['claim_lines.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_line_batch', 'payment_lines', ['batch_id'], unique=False)
    op.create_index('idx_payment_line_claim', 'payment_lines', ['claim_id'], unique=False)
    op.create_index('idx_payment_line_match', 'payment_lines', ['match_status'], unique=False)
    op.create_table('adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('payment_line_id', sa.UUID(), nullable=False),
    sa.Column('group_code', sa.String(length=5), nullable=False),
    sa.Column('reason_code', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('remark_codes', sa.ARRAY(sa.String(length=20)), nullable=True),
    sa.Column('is_denial', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_line_id'], ['payment_lines.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_adj_payment_line', 'adjustments', ['payment_line_id'], unique=False)
    op.create_index('idx_adj_practice', 'adjustments', ['practice_id'], unique=False)
    op.create_index('idx_adj_reason', 'adjustments', ['reason_code'], unique=False)
    op.create_table('denials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('claim_line_id', sa.UUID(), nullable=True),
    sa.Column('adjustment_id', sa.UUID(), nullable=True),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('denial_date', sa.Date(), nullable=False),
    sa.Column('reason_code', sa.String(length=10), nullable=False),
    sa.Column('remark_codes', sa.ARRAY(sa.String(length=20)), nullable=True),
    sa.Column('denial_amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('recovery_probability', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('appeal_deadline', sa.Date(), nullable=True),
    sa.Column('timely_filing_deadline', sa.Date(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('recovered_amount', sa.Float(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adjustment_id'], ['adjustments.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['claim_line_id'], ['claim_lines.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_denials_category', 'denials', ['category'], unique=False)
    op.create_index('idx_denials_claim', 'denials', ['claim_id'], unique=False)
    op.create_index('idx_denials_deadline', 'denials', ['appeal_deadline'], unique=False)
    op.create_index('idx_denials_payer', 'denials', ['payer_id'], unique=False)
    op.create_index('idx_denials_practice', 'denials', ['practice_id'], unique=False)
    op.create_index('idx_denials_priority', 'denials', ['priority_score'], unique=False, postgresql_using='btree')
    op.create_index('idx_denials_status', 'denials', ['status'], unique=False)
    op.create_table('appeals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('denial_id', sa.UUID(), nullable=False),
    sa.Column('appeal_level', sa.Integer(), nullable=False),
    sa.Column('appeal_type', sa.String(length=30), nullable=True),
    sa.Column('letter_content', sa.Text(), nullable=False),
    sa.Column('letter_file_id', sa.Uuid(), nullable=True),
    sa.Column('supporting_docs', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('prompt_template_id', sa.String(length=100), nullable=True),
    sa.Column('guidelines_cited', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_date', sa.Date(), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('decision_amount', sa.Float(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['denial_id'], ['denials.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appeals_denial', 'appeals', ['denial_id'], unique=False)
    op.create_index('idx_appeals_follow_up', 'appeals', ['follow_up_date'], unique=False)
    op.create_index('idx_appeals_practice', 'appeals', ['practice_id'], unique=False)
    op.create_index('idx_appeals_status', 'appeals', ['status'], unique=False)
    op.create_table('portal_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=True),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachments', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('related_claim_id', sa.UUID(), nullable=True),
    sa.Column('related_charge_id', sa.UUID(), nullable=True),
    sa.Column('related_denial_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('requires_response', sa.Boolean(), nullable=False),
    sa.Column('response_deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['related_charge_id'], ['charge_entries.id'], ),
    sa.ForeignKeyConstraint(['related_claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['related_denial_id'], ['denials.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_practice', 'portal_messages', ['practice_id'], unique=False)
    op.create_index('idx_messages_thread', 'portal_messages', ['thread_id'], unique=False)
    op.create_index('idx_messages_unread', 'portal_messages', ['is_read', 'practice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_unread', table_name='portal_messages')
    op.drop_index('idx_messages_thread', table_name='portal_messages')
    op.drop_index('idx_messages_practice', table_name='portal_messages')
    op.drop_table('portal_messages')
    op.drop_index('idx_appeals_status', table_name='appeals')
    op.drop_index('idx_appeals_practice', table_name='appeals')
    op.drop_index('idx_appeals_follow_up', table_name='appeals')
    op.drop_index('idx_appeals_denial', table_name='appeals')
    op.drop_table('appeals')
    op.drop_index('idx_denials_status', table_name='denials')
    op.drop_index('idx_denials_priority', table_name='denials', postgresql_using='btree')
    op.drop_index('idx_denials_practice', table_name='denials')
    op.drop_index('idx_denials_payer', table_name='denials')
    op.drop_index('idx_denials_deadline', table_name='denials')
    op.drop_index('idx_denials_claim', table_name='denials')
    op.drop_index('idx_denials_category', table_name='denials')
    op.drop_table('denials')
    op.drop_index('idx_adj_reason', table_name='adjustments')
    op.drop_index('idx_adj_practice', table_name='adjustments')
    op.drop_index('idx_adj_payment_line', table_name='adjustments')
    op.drop_table('adjustments')
    op.drop_index('idx_payment_line_match', table_name='payment_lines')
    op.drop_index('idx_payment_line_claim', table_name='payment_lines')
    op.drop_index('idx_payment_line_batch', table_name='payment_lines')
    op.drop_table('payment_lines')
    op.drop_index('idx_scrub_severity', table_name='claim_scrub_results')
    op.drop_index('idx_scrub_claim', table_name='claim_scrub_results')
    op.drop_table('claim_scrub_results')
    op.drop_index('idx_claim_lines_cpt', table_name='claim_lines')
    op.drop_index('idx_claim_lines_claim', table_name='claim_lines')
    op.drop_table('claim_lines')
    op.drop_index('idx_claim_dx_code', table_name='claim_diagnoses')
    op.drop_index('idx_claim_dx_claim', table_name='claim_diagnoses')
    op.drop_table('claim_diagnoses')
    op.drop_index('idx_coding_status', table_name='coding_sessions')
    op.drop_index('idx_coding_practice', table_name='coding_sessions')
    op.drop_index('idx_coding_encounter', table_name='coding_sessions')
    op.drop_index('idx_coding_coder', table_name='coding_sessions')
    op.drop_table('coding_sessions')
    op.drop_index('idx_claims_submission', table_name='claims')
    op.drop_index('idx_claims_status', table_name='claims')
    op.drop_index('idx_claims_practice', table_name='claims')
    op.drop_index('idx_claims_payer', table_name='claims')
    op.drop_index('idx_claims_patient', table_name='claims')
    op.drop_index('idx_claims_number', table_name='claims')
    op.drop_index('idx_claims_encounter', table_name='claims')
    op.drop_table('claims')
    op.drop_index('idx_charges_status', table_name='charge_entries')
    op.drop_index('idx_charges_practice', table_name='charge_entries')
    op.drop_index('idx_charges_date', table_name='charge_entries')
    op.drop_index('idx_charges_assigned', table_name='charge_entries')
    op.drop_table('charge_entries')
    op.drop_index('idx_queue_type_status', table_name='work_queue_items')
    op.drop_index('idx_queue_sla', table_name='work_queue_items', postgresql_where=sa.text('sla_breached = TRUE'))
    op.drop_index('idx_queue_priority', table_name='work_queue_items')
    op.drop_index('idx_queue_practice', table_name='work_queue_items')
    op.drop_index('idx_queue_assigned', table_name='work_queue_items')
    op.drop_table('work_queue_items')
    op.drop_index('idx_productivity_user', table_name='staff_productivity')
    op.drop_index('idx_productivity_practice', table_name='staff_productivity')
    op.drop_table('staff_productivity')
    op.drop_index('idx_assignments_user', table_name='staff_assignments')
    op.drop_index('idx_assignments_practice', table_name='staff_assignments')
    op.drop_table('staff_assignments')
    op.drop_index('idx_notifications_user', table_name='portal_notifications')
    op.drop_index('idx_notifications_unread', table_name='portal_notifications')
    op.drop_table('portal_notifications')
    op.drop_index('idx_payment_batch_status', table_name='payment_batches')
    op.drop_index('idx_payment_batch_practice', table_name='payment_batches')
    op.drop_index('idx_payment_batch_payer', table_name='payment_batches')
    op.drop_index('idx_payment_batch_check', table_name='payment_batches')
    op.drop_table('payment_batches')
    op.drop_index('idx_enrollments_practice', table_name='payer_enrollments')
    op.drop_index('idx_enrollments_payer', table_name='payer_enrollments')
    op.drop_table('payer_enrollments')
    op.drop_index('idx_fsr_schedule', table_name='fee_schedule_rates')
    op.drop_index('idx_fsr_cpt', table_name='fee_schedule_rates')
    op.drop_table('fee_schedule_rates')
    op.drop_index('idx_encounters_status', table_name='encounters')
    op.drop_index('idx_encounters_practice', table_name='encounters')
    op.drop_index('idx_encounters_patient', table_name='encounters')
    op.drop_index('idx_encounters_date', table_name='encounters')
    op.drop_table('encounters')
    op.drop_index('idx_coverages_practice', table_name='coverages')
    op.drop_index('idx_coverages_payer', table_name='coverages')
    op.drop_index('idx_coverages_patient', table_name='coverages')
    op.drop_index('idx_coverages_member', table_name='coverages')
    op.drop_table('coverages')
    op.drop_index('idx_charge_batches_status', table_name='charge_batches')
    op.drop_index('idx_charge_batches_practice', table_name='charge_batches')
    op.drop_table('charge_batches')
    op.drop_index('idx_users_type', table_name='users')
    op.drop_index('idx_users_practice', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_agreements_practice', table_name='service_agreements')
    op.drop_table('service_agreements')
    op.drop_index('idx_locations_practice', table_name='practice_locations')
    op.drop_table('practice_locations')
    op.drop_index('idx_payer_rules_type', table_name='payer_rules')
    op.drop_index('idx_payer_rules_payer', table_name='payer_rules')
    op.drop_index('idx_payer_rules_cpt', table_name='payer_rules')
    op.drop_table('payer_rules')
    op.drop_index('idx_patients_practice', table_name='patients')
    op.drop_index('idx_patients_name', table_name='patients')
    op.drop_index('idx_patients_mrn', table_name='patients')
    op.drop_index('idx_patients_dob', table_name='patients')
    op.drop_table('patients')
    op.drop_table('fee_schedules')
    op.drop_index('idx_invoices_status', table_name='client_invoices')
    op.drop_index('idx_invoices_practice', table_name='client_invoices')
    op.drop_index('idx_invoices_period', table_name='client_invoices')
    op.drop_table('client_invoices')
    op.drop_table('providers')
    op.drop_index('idx_practices_tin', table_name='practices')
    op.drop_index('idx_practices_status', table_name='practices')
    op.drop_table('practices')
    op.drop_table('permissions')
    op.drop_index('idx_payers_type', table_name='payers')
    op.drop_index('idx_payers_pid', table_name='payers')
    op.drop_table('payers')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
